### PR TITLE
README: better document questions and react children APIs

### PR DESCRIPTION
**Pull request by xaiki**
Even though i'm not really happy about the type/key API situation, i think questions and react API deserve a bit more doc.

### CODE REVIEW

**Comment by theiliad** [comment]
Yes, thanks again!
Regarding the input types, I'm also not finding adding the types to spans the best approach. We're still in the beginning phases, so we can explore different options to make sure we choose the best one down the road.

**Review by theiliad — APPROVED** [review]

**Comment by xaiki** [comment]
maybe the `for` keyword from the HTML form spec is what we want ? (used in `<label for="inputName">`)
or we have the `name` keyword too, (used in `<input name="inputName"/>`)

**Comment by theiliad** [comment]
What about doing this:
```jsx
<EurekaForm.TelInput />
<EurekaForm.EmailInput />
<EurekaForm.FileInput />
```

**Comment by theiliad** [comment]
All those components would extend `EurekaForm.Input` and inherit common properties, and offer some type specific functionality as well if need be

**Comment by xaiki** [comment]
As a matter of fact I had not seen those comments :)

So right now, <Question> is your <EurekaForm.Input>, I feel we'd still want to have a type key to handle all that are really just HTML5 inputs (that could grow) and have a collection of more complex inputs, so you can have TypeAheadQuestion with type="email" or a MapQuestion with type="tel" (where you'd select the country on a map and type the number, poor ui but it's just to make the point)

Right now I'm needing a kind of TypeAheadMapQuestion where you'd select a complex object filtering by geography and name from a known list.

**Pull request merged**
